section:
    - name: Receptive Language Section
      quiz_template_path: quiz_sections/section_1
      score_template_path: score_sections/section_1
      question:
        - template_path: quiz_sections/section_1/question_1
        - template_path: quiz_sections/section_1/question_2
    - name: Expressive Language Section
      quiz_template_path: quiz_sections/section_2
      score_template_path: score_sections/section_2
      question:
        - template_path: quiz_sections/section_2/question_1
        - template_path: quiz_sections/section_2/question_2

